### ISSUE TITLE
Problem with the translation file 'ts' in transifex for deepin-device-manager

### ISSUE THREAD

**Issue by roxfr** [linuxdeepin/deepin-devicemanager#1]
Hello,
I have a problem uploading the translation file 'ts' to transifex for deepin-device-manager.
I spotted an empty line toward position 2274.
Cordially.

**Comment by z966768** [comment]
Please elaborate, we can't understand

**Comment by PythonManGH** [comment]
Can you describe it in more detail ，What is 2274？

**Comment by PythonManGH** [comment]
> Hello,
> I have a problem uploading the translation file 'ts' to transifex for deepin-device-manager.
> I spotted an empty line toward position 2274.
> Cordially.

Can you describe it in more detail ，What is 2274？

**Comment by roxfr** [comment]
Hi,
The request is obsolete.
I close the problem.
Thank you
