### ISSUE TITLE
[Bug Report] 搜狗中文输入模式下打开设备管理器首次无法正确输入密码

### ISSUE THREAD

**Issue by happyd0ggie** [linuxdeepin/deepin-devicemanager#2]
## 缺陷描述

在搜狗输入法中文输入模式下, 打开设备管理器, 在弹出的认证框中, 第一次无法正确输入密码

## 复现步骤

1. 打开 '设备管理器'
2. 弹出授权认证对话框
3. 输入密码
4. 无法按回车键确认密码

## 期望行为

能够正常输入正确的密码, 自动切换输入法为英文输入模式

## 截图

[无法正确输入密码](https://ftp.bmp.ovh/imgs/2020/09/236a4c258982695e.png)

### 发行版以及版本

```
OS: Deepin 20
Kernel: x86_64 Linux 5.4.50-amd64-desktop
Uptime: 20h 47m
Packages: 2995
Shell: bash
Resolution: 2720x1024
DE: Deepin 20
WM: KWin
GTK Theme: deepin-dark [GTK2/3]
Icon Theme: bloom
CPU: Intel Core i7-6700 @ 8x 4GHz [27.8°C]
GPU: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2)
RAM: 5770MiB / 15897MiB
```

### 相关的软件包版本

```
$ apt policy deepin-devicemanager
deepin-devicemanager:
  已安装：5.5.9.17-1
  候选： 5.5.9.17-1
  版本列表：
 *** 5.5.9.17-1 500
        500 https://community-packages.deepin.com/deepin apricot/main amd64 Packages
        100 /var/lib/dpkg/status
     5.5.1.2-2 500
        500 https://community-store-packages.deepin.com/appstore eagle/appstore amd64 Packages
$ apt policy sogoupinyin
sogoupinyin:
  已安装：2.3.1.0112
  候选： 2.3.1.0112
  版本列表：
 *** 2.3.1.0112 500
        500 https://community-store-packages.deepin.com/appstore eagle/appstore amd64 Packages
        100 /var/lib/dpkg/status
     2.2.0.0108 500
        500 https://community-packages.deepin.com/deepin apricot/non-free amd64 Packages
```

### 其他内容

点x清空密码后能够正常输入

**Comment by UOS-Python** [comment]
> ## 缺陷描述
> 在搜狗输入法中文输入模式下, 打开设备管理器, 在弹出的认证框中, 第一次无法正确输入密码
> 
> ## 复现步骤
> 1. 打开 '设备管理器'
> 2. 弹出授权认证对话框
> 3. 输入密码
> 4. 无法按回车键确认密码
> 
> ## 期望行为
> 能够正常输入正确的密码, 自动切换输入法为英文输入模式
> 
> ## 截图
> [无法正确输入密码](https://ftp.bmp.ovh/imgs/2020/09/236a4c258982695e.png)
> 
> ## 复现环境:
> ### 发行版以及版本
> ```
> OS: Deepin 20
> Kernel: x86_64 Linux 5.4.50-amd64-desktop
> Uptime: 20h 47m
> Packages: 2995
> Shell: bash
> Resolution: 2720x1024
> DE: Deepin 20
> WM: KWin
> GTK Theme: deepin-dark [GTK2/3]
> Icon Theme: bloom
> CPU: Intel Core i7-6700 @ 8x 4GHz [27.8°C]
> GPU: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2)
> RAM: 5770MiB / 15897MiB
> ```
> 
> ### 相关的软件包版本
> ```
> $ apt policy deepin-devicemanager
> deepin-devicemanager:
>   已安装：5.5.9.17-1
>   候选： 5.5.9.17-1
>   版本列表：
>  *** 5.5.9.17-1 500
>         500 https://community-packages.deepin.com/deepin apricot/main amd64 Packages
>         100 /var/lib/dpkg/status
>      5.5.1.2-2 500
>         500 https://community-store-packages.deepin.com/appstore eagle/appstore amd64 Packages
> $ apt policy sogoupinyin
> sogoupinyin:
>   已安装：2.3.1.0112
>   候选： 2.3.1.0112
>   版本列表：
>  *** 2.3.1.0112 500
>         500 https://community-store-packages.deepin.com/appstore eagle/appstore amd64 Packages
>         100 /var/lib/dpkg/status
>      2.2.0.0108 500
>         500 https://community-packages.deepin.com/deepin apricot/non-free amd64 Packages
> ```
> 
> ### 其他内容
> 点x清空密码后能够正常输入

你好，建议你更新设备管理器，最新版已经不需要密码认证了

**Comment by happyd0ggie** [comment]
> > ## 缺陷描述
> > 在搜狗输入法中文输入模式下, 打开设备管理器, 在弹出的认证框中, 第一次无法正确输入密码
> > ## 复现步骤
> > 
> > 1. 打开 '设备管理器'
> > 2. 弹出授权认证对话框
> > 3. 输入密码
> > 4. 无法按回车键确认密码
> > 
> > ## 期望行为
> > 能够正常输入正确的密码, 自动切换输入法为英文输入模式
> > ## 截图
> > [无法正确输入密码](https://ftp.bmp.ovh/imgs/2020/09/236a4c258982695e.png)
> > ## 复现环境:
> > ### 发行版以及版本
> > ```
> > OS: Deepin 20
> > Kernel: x86_64 Linux 5.4.50-amd64-desktop
> > Uptime: 20h 47m
> > Packages: 2995
> > Shell: bash
> > Resolution: 2720x1024
> > DE: Deepin 20
> > WM: KWin
> > GTK Theme: deepin-dark [GTK2/3]
> > Icon Theme: bloom
> > CPU: Intel Core i7-6700 @ 8x 4GHz [27.8°C]
> > GPU: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2)
> > RAM: 5770MiB / 15897MiB
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 相关的软件包版本
> > ```
> > $ apt policy deepin-devicemanager
> > deepin-devicemanager:
> >   已安装：5.5.9.17-1
> >   候选： 5.5.9.17-1
> >   版本列表：
> >  *** 5.5.9.17-1 500
> >         500 https://community-packages.deepin.com/deepin apricot/main amd64 Packages
> >         100 /var/lib/dpkg/status
> >      5.5.1.2-2 500
> >         500 https://community-store-packages.deepin.com/appstore eagle/appstore amd64 Packages
> > $ apt policy sogoupinyin
> > sogoupinyin:
> >   已安装：2.3.1.0112
> >   候选： 2.3.1.0112
> >   版本列表：
> >  *** 2.3.1.0112 500
> >         500 https://community-store-packages.deepin.com/appstore eagle/appstore amd64 Packages
> >         100 /var/lib/dpkg/status
> >      2.2.0.0108 500
> >         500 https://community-packages.deepin.com/deepin apricot/non-free amd64 Packages
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 其他内容
> > 点x清空密码后能够正常输入
> 
> 你好，建议你更新设备管理器，最新版已经不需要密码认证了

已更新到UOS家庭版，确实是不需要密码认证了。
