### ISSUE TITLE
Realtek Bluetooth Radio蓝牙设备驱动推荐

### ISSUE THREAD

**Issue by patiencewu** [linuxdeepin/deepin-devicemanager#5]
原Deepin自带的蓝牙驱动, 对RealtekBluetoothRadio蓝牙设备支持较差, 会有多次出现链接不上, 显示"无法链接**"等信息,
经过本人机子自测, RealtekBluetoothRadio官方提供的蓝牙驱动, 可以完美支持, 推荐官方收录或集成, 详情如下:
机子型号: 荣耀笔记本Pro 2020新款 锐龙板(MagicBookPro)
蓝牙信息(因涉及隐私, 部分信息已隐藏): 
名称 : **********
制造商 : Realtek
版本 : 0.00
型号 : Realtek Bluetooth Radio
逻辑名称 : Bluetooth Radio
总线信息 : usb@3:4
功能 : bluetooth usb-1.00
驱动 : rtk_btusb
最大功率 : 500mA
速度 : 12Mbit/s
供电 : yes
可发现 : no
可配对 : yes
子版本 : 0x3d5f
序列号 : ********
总线 : USB
搜索中 : no
数据包类型 : DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3
服务类别 : Rendering, Capturing, Object Transfer
特征 : 0xff 0xff 0xff 0xfe 0xdb 0xfd 0x7b 0x87
类别 : 0x001c010c
蓝牙设备地址 : ******
设备 : Bluetooth Radio
设备类别 : Computer, Laptop
设置命令别名 : ******
连接模式 : SLAVE ACCEPT
连接策略 : RSWITCH HOLD SNIFF PARK

**Comment by z966768** [comment]
感谢您的建议,已收集,有进度会再次通知

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
