### ISSUE TITLE
Tag 5.6.6 与 5.6.7 与 5.6.8 之间到底是什么关系?

### ISSUE THREAD

**Issue by Rabenda** [linuxdeepin/deepin-devicemanager#7]

**Comment by UOS-Python** [comment]
> _No description provided._

功能上没有区别，主要是修复了部分bug

**Comment by Rabenda** [comment]
明显都不是一个分支 然后有版本号语义的tag？
这样的话如何跟进版本

**Comment by UOS-Python** [comment]
> 明显都不是一个分支 然后有版本号语义的tag？
> 这样的话如何跟进版本

您好，5.6已经进入维护线，现在是多个维护线共用一个tag线，后期的版本更新不会收到影响的。

**Comment by Rabenda** [comment]
> > 明显都不是一个分支 然后有版本号语义的tag？
> > 这样的话如何跟进版本
> 
> 您好，5.6已经进入维护线，现在是多个维护线共用一个tag线，后期的版本更新不会收到影响的。

但是语义化版本不是一条线的话 其他发行版维护起来非常麻烦
之后会提示哪个版本tag是哪个维护线的吗

**Comment by UOS-Python** [comment]
> > > 明显都不是一个分支 然后有版本号语义的tag？
> > > 这样的话如何跟进版本
> > 
> > 
> > 您好，5.6已经进入维护线，现在是多个维护线共用一个tag线，后期的版本更新不会收到影响的。
> 
> 但是语义化版本不是一条线的话 其他发行版维护起来非常麻烦
> 之后会提示哪个版本tag是哪个维护线的吗

您好，这个不会提示，5.6是作为一个研发阶段的tag，下一阶段会是5.7，我们会在5.7阶段考虑您提出的问题

**Comment by Sky-Asher** [comment]
您好，目前5.6.x已是维护线版本，现阶段新功能会在5.7.x进行。
每次新功能迭代，前两位数字会递增（5.6 -> 5.7），最后一位的变化仅仅是当前版本的bugfix（5.6.1 -> 5.6.2）,希望对您有帮助。

**Comment by Sky-Asher** [comment]
已超过一个月无人反馈，此问题即将被关闭，感谢您对UOS的支持！
