### ISSUE TITLE
Rep

### ISSUE THREAD

**Issue by SudoDios** [linuxdeepin/deepin-devicemanager#8]
sudo apt-get install deepin-devicemanager
not found package.

**Comment by Sky-Asher** [comment]
Run sudo apt-get update first, then apt policy deepin-devicemanager.Check whether there are candidate versions.
As shown in the figure below:
![image](https://user-images.githubusercontent.com/79684832/139526305-b6a6f459-8ff5-4c2a-99df-555c81f913a6.png)

**Comment by SudoDios** [comment]
I run **sudo apt-get update first, then apt policy deepin-devicemanager**.
result : 
![Screenshot from 2021-10-30 20-17-56](https://user-images.githubusercontent.com/62701838/139541944-68263f86-2e58-40f9-bbf8-1828dffb01fd.png)

**Comment by SudoDios** [comment]
What is repository to add apt ??

**Comment by Sky-Asher** [comment]
ubuntu 20.04.？Are you sure you are using UOS system?

**Comment by SudoDios** [comment]
I do not use UOS.  
My Ubuntu Linux is based on Debian.

**Comment by Sky-Asher** [comment]
I'm sorry.
There are no sources and dependencies on the ubantu, so you need to install the deepin-devicemanager in the UOS system.

**Comment by SudoDios** [comment]
Ok 👌.
Thanks

**Comment by Sky-Asher** [comment]
Maybe you can try UOS.
